services:
  postgres:
    image: 'postgres:18.1-alpine'
    container_name: postgresql
    environment:
      - 'POSTGRES_DB=pagination_demo_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      #- postgres-data:/var/lib/postgresql/data
      - ./compose:/docker-entrypoint-initdb.d

#volumes:
#  postgres-data: