spring:
  application:
    name: pagination-demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ./compose.yaml
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        arguments:
          - "-v"
          - "--remove-orphans"
          - "--timeout=1"
        timeout: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/pagination_demo_db
    username: app_user
    password: passw0rd
    hikari:
      data-source-properties:
        sslmode: disable
  jpa:
    hibernate:
      ddl-auto: none # initialization done in init-db in order to load the database with 1_000_000 records
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: pagination_demo_schema
  sql:
    init:
      mode: always

logging:
  level:
    nl.hakktastic: DEBUG
    org.springframework.data.jdbc: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([%30.30t]){faint} %clr(%-60.60logger{39}){cyan} %clr(:){faint} %m%n"